name: Harica CA tests

on:
  push:
    branches: [ 'devel', 'master']
  pull_request:
    branches: [ devel ]
  schedule:
    - cron:  '0 2 * * 6'

jobs:
  container_build:
    name: "container_build"
    runs-on: ubuntu-latest
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi']

    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v4

    - name: "Build container"
      uses: ./.github/actions/container_build_upload
      with:
        DB_HANDLER: ${{ matrix.dbhandler }}
        WEB_SRV: ${{ matrix.websrv }}

  acme_ca_handler_test:
    name: "acme_ca_handler_test"
    runs-on: ubuntu-latest
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    needs: container_build
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2', 'nginx']
        dbhandler: ['wsgi']

    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v4

    - name: Parse HARICA config
      uses: ./.github/actions/parse-json-secret
      with:
        json_secret: ${{ secrets.HARICA_CFG }}

    - name: "Download container"
      uses: actions/download-artifact@v4
      with:
        name: a2c-${{ github.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar.gz
        path: /tmp

    - name: "Import container"
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --batch --yes --no-tty --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update
        sudo apt install -y docker-compose-plugin
        gunzip /tmp/a2c-${{ github.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar.gz
        docker load -i /tmp/a2c-${{ github.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar
        docker images

    - name: "Prepare container environment"
      uses: ./.github/actions/container_prep
      with:
        DB_HANDLER: ${{ matrix.dbhandler }}
        WEB_SRV: ${{ matrix.websrv }}
        CONTAINER_BUILD: false

    - name: "Generate UUID"
      run: |
        echo UUID=$(uuidgen | cut -d "-" -f1) >> $GITHUB_ENV
    - run: echo "UUID ${{ env.UUID }}"

    - name: "Setup acme_ca_handler"
      run: |
        sudo mkdir -p examples/Docker/data/acme
        sudo chmod -R 777 examples/Docker/data/acme
        sudo cp .github/openssl_ca_handler.py_acme_srv_default_handler.cfg examples/Docker/data/acme_srv.cfg
        sudo chmod 777 examples/Docker/data/acme_srv.cfg
        sudo head -n -8 .github/openssl_ca_handler.py_acme_srv_default_handler.cfg > examples/Docker/data/acme_srv.cfg
        sudo echo "handler_file: examples/ca_handler/acme_ca_handler.py" >> examples/Docker/data/acme_srv.cfg
        sudo echo "acme_keyfile: volume/acme/harica_staging_private_key.json" >> examples/Docker/data/acme_srv.cfg
        sudo echo "acme_url: $ACME_URL" >> examples/Docker/data/acme_srv.cfg
        sudo echo "account_path: /acct/" >> examples/Docker/data/acme_srv.cfg
        sudo echo "acme_account_email: $ACME_ACCOUNT_EMAIL" >> examples/Docker/data/acme_srv.cfg
        sudo echo "eab_kid: $EAB_KID" >> examples/Docker/data/acme_srv.cfg
        sudo echo "eab_hmac_key: $EAB_HMAC_KEY" >> examples/Docker/data/acme_srv.cfg
        sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" examples/Docker/data/acme_srv.cfg
        sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\ncert_reusage_timeframe: 1800\nenrollment_timeout: 15\ncert_operations_log: True/g" examples/Docker/data/acme_srv.cfg
        sudo echo "allowed_domainlist: [\"*.$DOMAIN\", \"*.acme\"]" >> examples/Docker/data/acme_srv.cfg
      env:
        ACME_ACCOUNT_EMAIL: ${{ secrets.EMAIL }}

    - name: "Bring up a2c container"
      uses: ./.github/actions/container_up
      with:
        DB_HANDLER: ${{ matrix.dbhandler }}
        WEB_SRV: ${{ matrix.websrv }}

    - name: "Test enrollment"
      uses: ./.github/actions/wf_specific/harica/acme_enroll
      with:
        DEPLOYMENT_TYPE: "container"
        HOSTNAME_SUFFIX: -${{ env.UUID }}

    - name: "Check acme account found in keyfile"
      run: |
        cd examples/Docker
        docker compose logs | grep -i "found in keyfile"

    - name: "Check container configuration"
      uses: ./.github/actions/container_check
      with:
        DB_HANDLER: ${{ matrix.dbhandler }}
        WEB_SRV: ${{ matrix.websrv }}

    - name: "[ * ] collecting test data"
      if: ${{ failure() }}
      run: |
        mkdir -p ${{ github.workspace }}/artifact/upload
        sudo cp -rp examples/Docker/data/ ${{ github.workspace }}/artifact/data/
        cd examples/Docker
        docker compose logs > ${{ github.workspace }}/artifact/docker-compose.log
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz data docker-compose.log

    - name: "[ * ] uploading artifacts"
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: acme_ca_handler_test-${{ matrix.websrv }}-${{ matrix.dbhandler }}.tar.gz
        path: ${{ github.workspace }}/artifact/upload/

  cleanup:
    name: "cleanup"
    runs-on: ubuntu-latest
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    needs: [acme_ca_handler_test]
    strategy:
      fail-fast: false
      matrix:
        websrv: ['apache2']
        dbhandler: ['wsgi']

    steps:
    - uses: geekyeggo/delete-artifact@v5
      with:
        name: a2c-${{ github.run_id }}.${{ matrix.websrv }}.${{ matrix.dbhandler }}.tar.gz


  rpm_build_and_upload:
    name: "rpm_build_and_upload"
    runs-on: ubuntu-latest
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v4

    - name: "Build rpm package"
      id: rpm_build
      uses: ./.github/actions/rpm_build_upload


  rpm_acme_ca_handler_test:
    name: "rpm_acme_ca_handler_test"
    runs-on: ubuntu-latest
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    needs: [rpm_build_and_upload]
    strategy:
      fail-fast: false
      matrix:
        rhversion: [8, 9]

    steps:
    - name: "checkout GIT"
      uses: actions/checkout@v4

    - name: "Prepare Alma environment"
      uses: ./.github/actions/rpm_prep
      with:
        GH_SBOM_USER: ${{ secrets.GH_SBOM_USER }}
        GH_SBOM_TOKEN: ${{ secrets.GH_SBOM_TOKEN }}
        RH_VERSION: ${{ matrix.rhversion }}
        RPM_BUILD: false

    - name: Download rpm package
      uses: actions/download-artifact@v4
      with:
        name: acme2certifier-${{ github.run_id }}.noarch.rpm
        path: data/

    - name: Parse HARICA config
      uses: ./.github/actions/parse-json-secret
      with:
        json_secret: ${{ secrets.HARICA_CFG }}


    - name: "Generate UUID"
      run: |
        echo UUID=$(uuidgen | cut -d "-" -f1) >> $GITHUB_ENV
    - run: echo "UUID ${{ env.UUID }}"

    - name: "Setup acme_ca_handler"
      run: |
        sudo mkdir -p data/acme
        sudo chmod -R 777 data/acme
        sudo cp .github/openssl_ca_handler.py_acme_srv_default_handler.cfg data/acme_srv.cfg
        sudo chmod 777 data/acme_srv.cfg
        sudo head -n -8 .github/openssl_ca_handler.py_acme_srv_default_handler.cfg > data/acme_srv.cfg
        sudo echo "handler_file: examples/ca_handler/acme_ca_handler.py" >> data/acme_srv.cfg
        sudo echo "acme_keyfile: volume/acme/harica_staging_private_key.json" >> data/acme_srv.cfg
        sudo echo "acme_url: $ACME_URL" >> data/acme_srv.cfg
        sudo echo "account_path: /acct/" >> data/acme_srv.cfg
        sudo echo "acme_account_email: $ACME_ACCOUNT_EMAIL" >> data/acme_srv.cfg
        sudo echo "eab_kid: $EAB_KID" >> data/acme_srv.cfg
        sudo echo "eab_hmac_key: $EAB_HMAC_KEY" >> data/acme_srv.cfg
        sudo sed -i "s/challenge_validation_disable: False/challenge_validation_disable: True/g" data/acme_srv.cfg
        sudo echo "allowed_domainlist: [\"*.$DOMAIN\", \"*.acme\"]" >> data/acme_srv.cfg
        sudo sed -i "s/revocation_reason_check_disable: False/revocation_reason_check_disable: False\ncert_reusage_timeframe: 1800\nenrollment_timeout: 15\ncert_operations_log: True/g" data/acme_srv.cfg
      env:
        ACME_ACCOUNT_EMAIL: ${{ secrets.EMAIL }}

    - name: "Run Execute install scipt"
      run: |
        docker exec acme-srv sh /tmp/acme2certifier/rpm_tester.sh

    - name: "Test enrollment"
      uses: ./.github/actions/wf_specific/harica/acme_enroll
      with:
        DEPLOYMENT_TYPE: "rpm"
        HOSTNAME_SUFFIX: -${{ env.UUID }}

    - name: "[ * ] collecting test logs"
      if: ${{ failure() }}
      run: |
        docker logs acme-le-sim > ${{ github.workspace }}/artifact/le-sim.log
        mkdir -p ${{ github.workspace }}/artifact/upload
        docker exec acme-srv tar cvfz /tmp/acme2certifier/a2c.tgz /opt/acme2certifier
        sudo cp -rp data/ ${{ github.workspace }}/artifact/data/
        sudo rm ${{ github.workspace }}/artifact/data/*.rpm
        sudo cp -rp acme-sh/ ${{ github.workspace }}/artifact/acme-sh/
        docker exec acme-srv cat /etc/nginx/nginx.conf.orig > ${{ github.workspace }}/artifact/data/nginx.conf.orig
        docker exec acme-srv cat /etc/nginx/nginx.conf > ${{ github.workspace }}/artifact/data/nginx.conf
        docker exec acme-srv cat /var/log/messages > ${{ github.workspace }}/artifact/acme-srv.log
        sudo tar -C ${{ github.workspace }}/artifact/ -cvzf ${{ github.workspace }}/artifact/upload/artifact.tar.gz data acme-srv.log acme-sh

    - name: "[ * ] uploading artificates"
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: rpm_acme_ca_handler_test-rh${{ matrix.rhversion }}.tar.gz
        path: ${{ github.workspace }}/artifact/upload/


  rpm_cleanup:
    name: "rpm_cleanup"
    runs-on: ubuntu-latest
    # Prevent workflows from running in forks
    if: github.repository == 'grindsa/acme2certifier'
    needs: [rpm_build_and_upload, rpm_acme_ca_handler_test]
    steps:
    - name: "Delete artifact"
      uses: geekyeggo/delete-artifact@v5
      with:
        name: acme2certifier-${{ github.run_id }}.noarch.rpm
